const profiles = [
    {
      id: 1,
      image: "https://img.freepik.com/premium-photo/handsome-young-man-isolated-background-pointing-side-present-product_1368-40896.jpg?semt=ais_hybrid",
      name: "John Doe",
      location: "New York, USA",
      hobbies: ["Photography , Traveling , Coding"],
      about: ["A passionate developer who loves creating user-centric applications."],
    },
    {
      id: 2,
      image: "https://img.freepik.com/free-photo/vertical-shot-happy-dark-skinned-female-with-curly-hair_273609-15519.jpg?semt=ais_hybrid", 
      name: "Jane Smith",
      location: "London, UK",
      hobbies: ["Drawing , Writing , Yoga"],
      about: ["Graphic designer and storyteller through digital art and visuals."],
    },
    {
      id: 3,
      image: "https://via.placeholder.com/150",
      name: "Alice Brown",
      location: "Sydney, Australia",
      hobbies: ["Blogging , Gardening , Photography"],
      about: ["Content creator sharing tech tips, tutorials, and personal growth stories."],
    },
    {
      id: 3,
      image: "https://via.placeholder.com/150",
      name: "Alice Brown",
      location: "Sydney, Australia",
      hobbies: ["Blogging", "Gardening", "Photography"],
      about: ["Content creator sharing tech tips, tutorials, and personal growth stories."],
    },
    {
      id: 3,
      image: "https://via.placeholder.com/150",
      name: "Alice Brown",
      location: "Sydney, Australia",
      hobbies: ["Blogging", "Gardening", "Photography"],
      about: ["Content creator sharing tech tips, tutorials, and personal growth stories."],
    },
    {
      id: 3,
      image: "https://img.freepik.com/free-photo/lifestyle-people-emotions-casual-concept-confident-nice-smiling-asian-woman-cross-arms-chest-confident-ready-help-listening-coworkers-taking-part-conversation_1258-59335.jpg?semt=ais_hybrid",
      name: "Alice Brown",
      location: "Sydney, Australia",
      hobbies: ["Blogging", "Gardening", "Photography"],
      about: ["Content creator sharing tech tips, tutorials, and personal growth stories."],
    },
    {
      id: 1,
      image: "https://via.placeholder.com/150",
      name: "John Doe",
      location: "New York, USA",
      hobbies: ["Photography , Traveling , Coding"],
      about: ["A passionate developer who loves creating user-centric applications."],
    },
    {
      id: 2,
      image: "https://via.placeholder.com/150", 
      name: "Jane Smith",
      location: "London, UK",
      hobbies: ["Drawing , Writing , Yoga"],
      about: ["Graphic designer and storyteller through digital art and visuals."],
    },
    {
      id: 3,
      image: "https://via.placeholder.com/150",
      name: "Alice Brown",
      location: "Sydney, Australia",
      hobbies: ["Blogging , Gardening , Photography"],
      about: ["Content creator sharing tech tips, tutorials, and personal growth stories."],
    },
    {
      id: 3,
      image: "https://via.placeholder.com/150",
      name: "Alice Brown",
      location: "Sydney, Australia",
      hobbies: ["Blogging", "Gardening", "Photography"],
      about: ["Content creator sharing tech tips, tutorials, and personal growth stories."],
    },
    {
      id: 3,
      image: "https://via.placeholder.com/150",
      name: "Alice Brown",
      location: "Sydney, Australia",
      hobbies: ["Blogging", "Gardening", "Photography"],
      about: ["Content creator sharing tech tips, tutorials, and personal growth stories."],
    },
    {
      id: 3,
      image: "https://via.placeholder.com/150",
      name: "Alice Brown",
      location: "Sydney, Australia",
      hobbies: ["Blogging", "Gardening", "Photography"],
      about: ["Content creator sharing tech tips, tutorials, and personal growth stories."],
    },
  ];
  
  export default profiles;
  